### ISSUE TITLE
Warning with location

### ISSUE THREAD

**Issue by dipiash** [mjrussell/redux-auth-wrapper#104]
Hi, all!

Warning: Failed prop type: The prop `location` is marked as required in `UserIsAuthenticated(Component)`, but its value is `undefined`.

```JSX
export const UserIsAuthenticated = userAuthWrapper({
	authSelector: () => (getCookie('token') !== '' ?
		{'atengine.auth.token': getCookie('token')}
		: null),
	redirectAction: routerActions.replace,
	wrapperDisplayName: 'UserIsAuthenticated',
	failureRedirectPath: '/auth/signin',
	failureComponent: null
});
```

This warning shows me when I use it by Decorator and use it by function:
```JSX
const AdminOnlyLink = UserIsAuthenticated (() => <div className='container'><Component/></>)
```

How to solve this problem? Help me please.

**Comment by mjrussell** [comment]
@dipiash what are you trying to do with the auth-wrapper? Are you trying to hide the rendered component? Is that why you are attempting to use failureComponent? The warning is caused because the auth-wrapper is attempting to perform a redirect but it is not probably being rendered at a Route level (and can't get the location property from react router). But it looks to me like you are actually trying to hide the component. 

The readme has an example of this [here](https://github.com/mjrussell/redux-auth-wrapper#hiding-components)

The code is:
```js
const VisibleOnlyAdmin = UserAuthWrapper({
  authSelector: state => state.user,
  wrapperDisplayName: 'VisibleOnlyAdmin',
  predicate: user => user.isAdmin,
  FailureComponent: null
})
```

In this case, `FailureComponent` is the property of the config object and must be capitalized accordingly (Im using the convention of capitalizing component names).

So your wrapper would become:

```js
export const UserIsAuthenticated = userAuthWrapper({
	authSelector: () => (getCookie('token') !== '' ?
		{'atengine.auth.token': getCookie('token')}
		: null),
	redirectAction: routerActions.replace,
	wrapperDisplayName: 'UserIsAuthenticated',
	failureRedirectPath: '/auth/signin',
	FailureComponent: null
});
```

**Comment by dipiash** [comment]
@mjrussell Thanks! It's help me :)

```jsx
failureComponent
```

```jsx
FailureComponent
```
