### ISSUE TITLE
Usage with React-Redux-Firebase

### ISSUE THREAD

**Issue by tushardhoot** [mjrussell/redux-auth-wrapper#114]
Hi,

I use firebase for authentication and I am trying to make it work with redux-auth-wrapper. react-redux-firebase provides some pointers on how to use redux-auth-wrapper [here](http://react-redux-firebase.com/docs/recipes/routing.html).

Based on that, here is my wrapper:

```
import { browserHistory } from 'react-router'
import { routerActions } from 'react-router-redux'
import { UserAuthWrapper } from 'redux-auth-wrapper'
import { helpers } from 'react-redux-firebase'
const { pathToJS } = helpers

export const UserIsAuthenticated = UserAuthWrapper({
  wrapperDisplayName: 'UserIsAuthenticated',
  authSelector: ({ firebase }) => pathToJS(firebase, 'auth'),
  authenticatingSelector: ({ firebase }) => pathToJS(firebase, 'isInitializing') === true,
  failureRedirectPath: '/login',
  redirectAction: routerActions.replace,
})
```

Currently, the wrapper seems to always think I'm logged out and therefore redirects me. I can get the auth object from my redux store in my component, but the wrapper is not able to (the object returned by `pathToJs()` is "undefined"). If I don't use the wrapper and just check for existence of the auth object myself in my component, everything works as expected.

Do you have any experience making redux-auth-wrapper work with firebase?

Thanks,

Tushar

**Comment by mjrussell** [comment]
@tushardhoot Im not familiar with firebase, however I think the issue in your case at least looking at the docs they linked is that the `firebase` prop is passed via `firebaseConnect`, instead of from the redux store which is where your `authSelector` is looking. So I think you might be able to do something like this:
```js
export const UserIsAuthenticated = UserAuthWrapper({
  wrapperDisplayName: 'UserIsAuthenticated',
  authSelector: (state, { firebase }) => pathToJS(firebase, 'auth'),
  authenticatingSelector: ({ firebase }) => pathToJS(firebase, 'isInitializing') === true,
  failureRedirectPath: '/login',
  redirectAction: routerActions.replace,
})
```
This is because the second argument to a "redux selector" function is the `ownProps` which are the props passed into the component.

Then we can use it with `firebaseConnect`:

es7 decorators:
```js
@firebaseConnect()
@UserIsAuthenticated
export default class MyComponent extends Component {
  ...
}
```

es5/6:
```js
class MyComponent extends Component {
  ...
}
export default firebaseConnect()(UserIsAuthenticated(MyComponent));
```


@prescottprue thanks for showing an example using redux-auth-wrapper! Do you think this is the correct approach?

**Comment by prescottprue** [comment]
@tushardhoot Feel free to file an issue of this on [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) so we can get it working correctly for you.

It might be as easy as adding a predicate like so:

```js
export const UserIsAuthenticated = UserAuthWrapper({ // eslint-disable-line new-cap
  wrapperDisplayName: 'UserIsAuthenticated',
  authSelector: ({ firebase }) => pathToJS(firebase, 'auth'),
  authenticatingSelector: ({ firebase }) => pathToJS(firebase, 'isInitializing') === true,
  predicate: auth => auth !== null,
 redirectAction: routerActions.replace
  // LoadingComponent: <p>Loading </p>, // nice for showing loading while auth is loading
});
```

@mjrussell Of course! `redux-auth-wrapper` has helped my team secure our routes and show/hide components throughout multiple of our applications. We all found it really nice and easy to implement.

**Comment by tushardhoot** [comment]
Thanks @mjrussell and @prescottprue. Adding the predicate fixed it!

Curious as to why this works. The default predicate also returns false if `authData` is `null` or `{}`, right? It doesn't seem like `authData` is `{}`, so why does explicitly checking for `null` fix it?

**Comment by prescottprue** [comment]
@tushardhoot Because it is `undefined` initially. After it loaded it is either `null` or it's value (whatever is on Firebase).

**Comment by tushardhoot** [comment]
@prescottprue Got it. Thanks both of you!

**Comment by andrewmartin** [comment]
Hey guys, 

I was stumbling on this right now , and I'm a bit confused. Do the recipes in the docs work? 

I have everything set up and working, but I'm seeing a flash on my Login screen, likely due to the fact that the Firebase app hasn't init'ed yet. I tried literally copy pasting as a decorator from the recipes, and I'm hitting a nasty error saying `Object is not a function`. 

I know this is fairly vague, but was just curious, do the recipes still work for Firebase? I'm on `"redux-auth-wrapper": "^2.0.1",`.

**Comment by prescottprue** [comment]
@andrewmartin They should be working. There are the two examples, the `redux-auth-wrapper` v2 example and v1 example (different syntax), as well as v1/v2 syntax differences with `react-redux-firebase`.

The material example will soon be using this, so if it isn't working as intended, we should get to the bottom of it. Feel free to open a new issue (might be good to clearly define a repro case).

**Comment by andrewmartin** [comment]
@prescottprue thanks. Can you point me to a working sample for react-router `v4`? I am assuming I'm looking at the same ones as you, but wanted to be 100% sure. I'm seeing a flash before Firebase is ready, it basically hits the login screen and sends back. I copy pasted from the docs.
