### ISSUE TITLE
Docs might mislead new devs into calling hoc in a component render method

### ISSUE THREAD

**Issue by thezanke** [mjrussell/redux-auth-wrapper#115]
As the React docs say, you shouldn't call a hoc function in a Component `render()` method.

I admittedly don't know if it is or isn't safe to call them in `ReactDOM.render()`.

Like many others, however, I typically have my routes in a separate Routes component; using `userIsAuthenticated()` inside of <Routes> `render()` is certainly a no-no, right?

If that's the case I think the docs need a warning since, by showing them used within the Route `component={}`, it might encourage newer people to call it within the render methods of their components.

**Comment by mjrussell** [comment]
Yeah I think thats probably a good idea, you are right it could be easy to make a mistake by using render. Im going to list what I think are some good example and can update the docs if it looks good/useful:

#### My understanding is all the following are safe:

Directly inside ReactDOM.render:
```js
ReactDOM.render(
  <Provider store={store}>
    <Router history={history}>
      <Route path="/" component={App}>
        <Route path="auth" component={UserIsAuthenticated(Foo)}/>
        ...
      </Route>
    </Router>
  </Provider>,
  document.getElementById('mount')
)
```

Separate route config file:
```js
const routes = (
  <Route path="/" component={App}>
    <Route path="auth" component={UserIsAuthenticated(Foo)}/>
    ...
  </Route>
)

ReactDOM.render(  
  <Provider store={store}>
    <Router history={history}>
      {routes}
    </Router>
  </Provider>,
  document.getElementById('mount')
)
```

Applied in the component file (es7):
```js
@UserIsAuthenticated
export default class MyComponent extends Component {
  ...
}
```

Applied in the component file (es6):
```js
class MyComponent extends Component {
  ...
}
export default UserIsAuthenticated(MyComponent)
```

Applied outside the component file:
```js
import MyComponent from './component/mycomponent.js'

const MyAuthComponent = UserIsAuthenticated(MyComponent)
```

#### The following are not safe:
The following are all not safe because they create a new component over and over again, preventing react from considering these the "same" component and causing mounting/unmounting loops.

Inside of render:
```js
import MyComponent from './component/MyComponent.js'

class MyParentComponent extends Component {
  render() {
    const MyAuthComponent = UserIsAuthenticated(MyComponent)
    return <MyAuthComponent />
  }
}
```

Inside of `getComponent`:
```js
const routes = (
  <Route path="/" component={App}>
    <Route path="auth" getComponent={(nextState, cb) => { 
      cb(null, UserIsAuthenticated(Foo))
     }} />
     ...
  </Route>
)
```
