### ISSUE TITLE
How to test a decorated component?

### ISSUE THREAD

**Issue by wellnine** [mjrussell/redux-auth-wrapper#123]
Hi. I a working with this package and I have a simple decorated component that looks like

**@UnAuthorizedAccess
export default LandingPageModule extends React.Component....**

it works great but I don't know how to test this component? I tried to use the **redux-mock-store** package  but it isn't working for me. 

LandingPageModule.spec.js   file

**import React from "react";
import { mount } from "enzyme";

import { Provider } from "react-redux";
import configureStore  from "redux-mock-store";

import  { userClientModelImm } from "core/models";

const middlewares = [];
const mockStore = configureStore(middlewares);

const mockStoreInitialized = mockStore({
	userReducer : userClientModelImm
});

import LandingPageModule from "../LandingPage.module";

describe("LandingPageModule", () => {
	const wrapper = mount(
		<Provider store={mockStoreInitialized}>
			<LandingPageModule />
		</Provider>
	);**

I got an error:
"Warning: Failed prop type: The prop `location` is marked as required in `UnauthorizedAccessOnly(LandingPageModule)`, but its value is `undefined`.
    in UnauthorizedAccessOnly(LandingPageModule) (created by Connect(UnauthorizedAccessOnly(LandingPageModule)))
    in Connect(UnauthorizedAccessOnly(LandingPageModule))
    in Provider (created by Unknown)
    in Unknown'"

Maybe an other way exists to test decorated components? Thanks.

**Comment by mjrussell** [comment]
As with almost all testing, it depends on what you would like to test. If you would like to test that the wrapper is doing its job correctly (which really should be this library/my job but you are welcome to as well) you will need to pass in the required props which include the location and others. Feel free to look at the source, its not long in order to determine what those are  - https://github.com/mjrussell/redux-auth-wrapper/blob/master/src/index.js#L83-L88). And since the wrapper uses connect, you will need to set up a store/provider or some mock variation of it for the test.

In my opinion, you probably do not need to test the auth wrapper (except maybe your predicate functions but they can be tested as pure functions). Its the same way that you would not write a test to verify that `connect` from react-redux pulls data out of the store. 

Instead, I'd recommend that you export both the "unwrapped" and the "wrapped" components and test only the unwrapped one while providing it any props that would normally be passed down from the wrapper. This is exactly the same testing advice that redux provides and I'd recommend you read the following - https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md#connected-components
