### ISSUE TITLE
Why react-router is here?

### ISSUE THREAD

**Issue by Stupidism** [mjrussell/redux-auth-wrapper#135]
In my opinion, you're doing a very good repo. 
However, I don't figure it out why you tie this repo with together with `react-router`.

`react-router` is so heavy that if you drop it, you will find your repo much lighter and makes more sense.

Why `react-router` is [not necessary](https://medium.freecodecamp.com/you-might-not-need-react-router-38673620f3d)?

**Comment by Stupidism** [comment]
I looked at your code. 
Actually, you're not relying or importing `react-router` directly. 
But in your code, you are using something injected by `react-router`.
[line 129](https://github.com/mjrussell/redux-auth-wrapper/blob/master/src/index.js#L129)
[line 138](https://github.com/mjrussell/redux-auth-wrapper/blob/master/src/index.js#L138)

**Comment by Stupidism** [comment]
Maybe this repo should use name `react-redux-router-auth-wrapper` but not `redux-auth-wrapper`

**Comment by mjrussell** [comment]
If you look at the [Motiviation](https://github.com/mjrussell/redux-auth-wrapper#motivation) you can see that this repo was originally created to address a common problem faced by many users of React Router and redux. 

When I began working on this library about a year and a half ago, React Router provided a very nice routing solution, but offered up fairly unsatisfactory examples and solutions when adding both authentication and redux. This library was initially written for a project that did required React Router's nested routes and other advanced features and I found it so useful that it seemed worthwhile to open source. Over time as more users have provided their input and contributed code, it has become even more generic (Failure/Alternative Components) and decoupled both from React Router and even routing.

Because of the prevalence of React Router, I think shunning it completely would be a mistake and discourage users who could benefit from using the library to simplify their auth code. I've read the blog you linked below, I think it makes some good points, but I find it unlikely that people new to the ecosystem will try to use history directly rather than follow the multitude of React Router examples and support.

That being said, I definitely want to be flexible for as many people as possible. As you discovered by looking at the code, there is no hard dependency on React Router. In fact, you can use this project exactly as described in the post with history. The wrapper HOC will look for React-Router's context only when not passed a redirect action.

So you can pass in a `redirectAction` that either calls `history.push` or `history.replace` directly or uses a simple redux-middleware to encapsulate the history calls similar to what react-router-redux [does](https://github.com/reactjs/react-router-redux/blob/master/src/middleware.js).

As for the name, I'll go with the now infamous quote "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors." 😉

**Comment by Stupidism** [comment]
Thanks for your response! I will git it a try.
Maybe, this repo needs a doc for `no-react-router`.
BTW, new memo learned!

**Comment by mjrussell** [comment]
Agree on the documentation, I'd like to do a bit of a documentation overhaul at some point (maybe with gitbook). If you run into issues using it without react-router feel free to open an issue . I believe until #133 is merged, it will only support history 2/3 (not history 4). This is because of the changes to `location.query`. Although its certainly possible to pass a custom `redirectAction` that converts from `location.query` to `location.search`.

**Comment by oyeanuj** [comment]
@mjrussell +1 to the doc addition.  Another use-case that I had been thinking about that might also be relevant - for a project, I am considering use NextJS and they have their own router solution (or if someone is using `found`, etc). An example or some clarification in the doc would help those users!

**Comment by Stupidism** [comment]
[PR](https://github.com/mjrussell/redux-auth-wrapper/pull/139) was proposed a few days ago @mjrussell
