### ISSUE TITLE
Why am I getting null in the AuthWrapper?

### ISSUE THREAD

**Issue by moneytree-doug** [mjrussell/redux-auth-wrapper#141]
I can't figure out why this is happening, but I am going to a protected route when unauthenticated and it's redirecting me to ``/login?redirect=XXX``, but then it shows up as blank. When inspect with devtools, it'll say ``react-empty``. Looking through the React tools in Chrome devtools, it seems that inside the ``AuthWrapper`` has a ``null``.

```
const GuestIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.guest, // how to get the user state
  predicate: () => Cookie.get('accessToken') && !!Cookie.get('accessToken').length,
  authenticatingSelector: state => state.guest.isLoading,
  redirectAction: routerActions.replace, // the redux action to dispatch for redirect
  wrapperDisplayName: 'GuestIsAuthenticated', // a nice name for this auth check
});

const Authenticated = GuestIsAuthenticated(props => React.cloneElement(props.children, props));

          <Route component={Authenticated}>
            <Route path="guest/profile" component={GuestProfile} />
          </Route>
```

**Comment by mjrussell** [comment]
The only times a component created with user-auth-wrapper returns null is in two cases:
1. The authenticating selector returns a value that is not truthy (true, 0, etc) **and** you dont have an AuthenticatingComponent defined
2. The wrapper issues a redirect (because the authSelector returns something not truthy) and expects the router will redirect.

So I would first eliminate the authenticatingSelector as a test if you still see the same behavior then possibly you Login route at `/login` isn't being redirected to properly. Can you navigate to that URL independently of using redux-auth-wrapper?

**Comment by moneytree-doug** [comment]
@mjrussell

> Can you navigate to that URL independently of using redux-auth-wrapper?
Yes, I can. I'm trying to have that protected route redirect me to the login.

> 1. The authenticating selector returns a value that is not truthy (true, 0, etc) and you dont have an AuthenticatingComponent defined
I don't see this in the docs, but what is an AuthenticatingComponent ? Why do I need an authenticating component defined? 
> 2. The wrapper issues a redirect (because the authSelector returns something not truthy) and expects the router will redirect.
Why is the router not redirecting? So when I'm stuck in this state and just hit the refresh button, then it will redirect properly. Just to give more information, I'm actually having a request set to my componentWillMount in the highest level that will get the User's data. If it 401s, the my guest reducer will return a ``{}``

```

const initialState = {
  data: null,
  isLoading: false,
};
export const guestReducer = (state = initialState, action) => {
  switch (action.type) {
    case FETCH_GUESTS_REQUEST:
      return { data: null, isLoading: true };
    case FETCH_GUESTS_SUCCESS:
      return { data: action.response.body.guest, isLoading: false };
    case API_UNAUTHORIZED:
    case FETCH_GUESTS_FAILURE:
      return {};
    default:
      return state;
  }
};

```

**Comment by mjrussell** [comment]
Sorry I mean `LoadingComponent` when I said `AuthenticatingComponent`, you dont need one defined, but it will show null at that time if you dont override the field. Your original question asked when the AuthWrapper will render a null value.

If your URL bar updates, the auth-wrapper is likely doing its job, since it went all the way to the history object (via the router). 

I dont see anything immediately wrong with your example, I'd return `initialState` after `API_UNAUTHORIZED` and `FETCH_GUESTS_FAILURE` but you are handling those cases right now.

How is your Login component set up? Are you using redux-auth-wrapper there as well?

**Comment by moneytree-doug** [comment]
@mjrussell Sorry for lumping in more questions. The url is being redirected, but it's just null in the AuthWrapper. 

> How is your Login component set up? Are you using redux-auth-wrapper there as well?
Yes I am using redux-auth-wrapper as well. I'm not sure how should I describe how my LoginComponent is setup. I have route for login, and that's nested under my App component. My app component's componentWillMount will send an API call and then dispatch the success/error/API_UNAUTHORIZED on all pages except for the login. So when I try to visit the protected route: ``guest/profile`` then it redirects to the login because of the 401.
```

          <Route path="login" component={Login} />
          <Route component={Authenticated}>
            <Route path="guest/profile" component={GuestProfile} />
          </Route>
```

**Comment by mjrussell** [comment]
The reason its null in the auth wrapper (unless you are also using another auth wrapper in Login - more on that below) is because the wrapper for GuestProfile performed the redirect and expects react-router to have performed a redirect but nothing happened. The auth-wrapper cannot render the child component (in this case GuestProfile) because there is no auth data, so there is nothing to render.

What I was wondering, (which I believe the answer is no from your code snipper) was if you were using another wrapper for the Login component in addition to your GuestProfile, this is because some code has to redirect users back to the page after they login. Here is an example in the [loading example](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L71).

**Comment by moneytree-doug** [comment]
@mjrussell So are you saying that I also have to decorate the Login as well with this library's wrapper?

Ex,

`const UserIsNotAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsNotAuthenticated',
  // Want to redirect the user when they are done loading and authenticated
  predicate: user => user.data === null && user.isLoading === false,
  failureRedirectPath: (state, ownProps) => ownProps.location.query.redirect || '/foo',
  allowRedirectBack: false
})

          <Route path="login" component={UserIsNotAuthenticated(Login)}/>`

**Comment by mt-nickjanssen** [comment]
We found out that the issue was caused by passing two different `history` objects for the middleware and the router, as per your comment [here](https://github.com/mjrussell/redux-auth-wrapper/issues/117).
Thanks for your help! (I'm @moneytree-doug 's colleague)

**Comment by mjrussell** [comment]
Ah yes, that would explain it. I should try to make a troubleshooting section of the documentation with common errors

**Comment by moneytree-doug** [comment]
@mjrussell Thanks again for answering all my questions!
