### ISSUE TITLE
Why is onEnter necessary for SSR to redirect?

### ISSUE THREAD

**Issue by sleungcy** [mjrussell/redux-auth-wrapper#149]
I cant understand why onEnter is necessary for server side rendering. Could someone please explain?

**Comment by mjrussell** [comment]
I don't think this is really a question for this library, but I'll try to explain it as best I can. You might have better luck asking in SO for regarding React Router or in the Discord channel. Warning, I don't use SSR and have never done it before, but have an idea from communicating with other devs and reading examples.

Redirection with redux-auth-wrapper typically is all done on the client, where it uses `history` to redirect to another page within the single page app. However, in a server side rendered application, you may have route splitting and some routes that a user should never reach if they are not authorized (like split the administration section of the app from the main one). If you dont use an onEnter or similar mechanism on the server, then the user will be sent all the client code for the admin area, possible only to be redirected out of it immediately. 

Ultimately I dont think you have to use the onEnter with SSR, I think you could still send the entire JS and redirect once they reach it, but I think the goal is to use the same auth checks on the server before sending the client code as you do on the client.

@oyeanuj was the one who originally requested this, maybe he can add something or correct me if Im wrong?

**Comment by sleungcy** [comment]
Thank you very much for this answer. I was confused by the documentation because 'onEnter' is under the "Server side rendering" section, but I understand the whole process now. UserAuthWrapper.onEnter adds a user authenticating layer on top of react-router's redirection logic, it validates the user object validity, then hijack and changes the location react-router is going. 

UserAuthWrapper has nothing to do with whether you are doing SSR or not. As long as you need UserAuthWrapper to redirect, you need to insert UserAuthWrapper.onEnter into the route.

It would make sense to move the documentation for onEnter out of the SSR section?

**Comment by mjrussell** [comment]
Hmm, not exactly, let my try to clarify.

redux-auth-wrapper does not use onEnter by default, the original intent of writing the library was because using onEnter is extremely clunky with redux connected user data and it also didn't re-check auth when the store changed (you can read more details in the Motivation of the README). Instead, redux-auth-wapper uses a HOC approach which wraps the component and performs the redirection using component lifecycle methods (willMount/willReceiveProps). It was my intention originally that people never use `onEnter` for auth checking.

However, people using SSR requested that redux-auth-wrapper include a an onEnter that performs the same check the HOC is doing in order to perform a redirection at the server, as opposed to rendering to HTML and sending down empty divs when the user is not authenticated/authorized

**Comment by sleungcy** [comment]
Ahhh, that make sense! Because you would not "Mount" anything when doing redirection in SSR! Thanks Matt for this explanation.
