### ISSUE TITLE
Renaming of UserAuthWrapper

### ISSUE THREAD

**Issue by tkvw** [mjrussell/redux-auth-wrapper#165]
First of all, thanks for this excellent library. Just a tiny improvement request; for readability I would like to suggest to rename UserAuthWrapper to "Guard". I think this makes more sense.

**Comment by mjrussell** [comment]
Thanks for the comment. Helps motivate me while Im in the home stretch of getting V2 out. I agree that `UserAuthWrapper` might not be the best name, naming things is one of the hardest problems in programming 😉 . I think others might disagree with your choice, and many people find this repo because of authentication/authorization. However you can easily use different names when you import this library to improve the readability of your code:

```js
import { UserAuthWrapper as Guard } from 'redux-auth-wrapper'

Guard({...})(Component)
```

You can even make a file called `guard.js` if you dont want always do the qualified import:
```js
import { UserAuthWrapper as Guard } from 'redux-auth-wrapper'
export Guard
```

Then in your files:
```js
import Guard from './guard.js'
```

**Comment by tkvw** [comment]
Thanks for your quick response and helpful answer.
