### ISSUE TITLE
Question: Is this used for authentication too?

### ISSUE THREAD

**Issue by mittalabhas1** [mjrussell/redux-auth-wrapper#177]
Hey @mjrussell, I was looking out for a library like `redux-auth` that handles the authentication for you. I'm just curious if `redux-auth-wrapper` does that or the sole purpose of this is to manage the redirects for your application upon unauthenticated access?

**Comment by mjrussell** [comment]
redux-auth-wrapper is much more lightweight than redux-auth or other authentication frameworks. This library is focused solely on the redirection of users and display of components depending on details about the user. It doesn't handle storing the tokens/credentials of a user or requesting them from the server or ready to go components to plug into your application.

I find I prefer the greater flexibility to design my auth system how I see fit, but I can definitely see benefits to using redux-auth in order to get a project setup quickly and not spend time developing the auth system. I think you can also probably use redux-auth-wrapper in redux-auth react apps, for instance to hide buttons or other content based on data stored by redux-auth. But I haven't really gone through their repo enough.
