### ISSUE TITLE
jwt example with react-router-redux?

### ISSUE THREAD

**Issue by transtone** [mjrussell/redux-auth-wrapper#18]
https://github.com/mjrussell/react-redux-jwt-auth-example/tree/auth-wrapper
the jwt auth example is using redux-router, and the example is so diffrent with the react-router-redux one: it use "dispatch" in actions, and ```loginUser(email, password, redirect="/")``` function use ```dispatch(pushState(null, redirect));``` to redirect. 
how can I write a loginUser function to enhunce the basic example？ thanks。

**Comment by mjrussell** [comment]
Thanks, yeah its a bit different using `react-router-redux`. I'll work on updating the example to use react-router-redux and React-Router v2.

**Comment by mjrussell** [comment]
@transtone I've pushed a new branch to the forked jwt example. You can find it located here:
https://github.com/mjrussell/react-redux-jwt-auth-example/tree/react-router-redux

I've updated it to be current with react-router-redux and React-Router 2.0. I did not, however, change much of the logic from the original implementation so that people can compare with the original example more easily.

Let me know if the updated example clarifies things using JWT and react-router-redux or if there is more I can do. I hope to push a smaller and "simplified" server rendering with JWT or token authentication at some point soon but thats definitely a bit more involved.

**Comment by transtone** [comment]
react-router-redux is up to 4.0.0, some api was changed, please update the example.

**Comment by transtone** [comment]
It changes a lot:
https://github.com/davezuko/react-redux-starter-kit/commit/0df26907

**Comment by jjwon0** [comment]
yep, presumably due to the api breakage from `3.0` and `4.0.0`, this wrapper doesn't seem to work anymore.

**Comment by mjrussell** [comment]
The library should work with any redux + routing library, but you would need to change the redirect param to match their new one. I've been a little busy lately but will spend some time on this lib and get all the examples up to date this weekend.

**Comment by jjwon0** [comment]
I tried setting `redirectAction: push` and `redirectAction: replace`, where `push, replace` were imported; however, I couldn't get this to work.  It might be as simple as bumping `"react-router-redux": ~4.0.0" in the dependencies.

Let me know how it goes! :)

**Comment by mjrussell** [comment]
@jjwon0 I updated the tests and examples in this repo to v4 in #27 

@transtone I updated the jwt example in https://github.com/mjrussell/react-redux-jwt-auth-example/commit/5ed7a2e041cf24841e38bc40a980b83d3aa4ad07

Im going to close this, feel free to reopen or ask questions if you think there is work left to do
