### ISSUE TITLE
Hiding component from another file not working

### ISSUE THREAD

**Issue by romanlex** [mjrussell/redux-auth-wrapper#182]
Hello. I found what Hiding component from another file not working. Example:
**app/commong/acl.js**
```javascript
export const VisibleOnlyAdmin = authWrapper({
	authenticatedSelector: state => Object.keys(state.user.data).length !== 0 && state.user.isAuthenticated === true && state.user.data.role === 'admin',
	wrapperDisplayName: 'VisibleOnlyAdmin',
});
```
In Component I import VisibleOnlyAdmin:
```javascript
import { VisibleOnlyAdmin } from 'app/common/acl';
...
render() {
  return (
    <div>
       <VisibleOnlyAdmin>
            ....
       </VisibleOnlyAdmin>
    </div>
  )
}
```
I have error: 

> Warning: wrapComponent(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

But if I create visibleOnlyAmin in my Component - all work properly!
```javascript
const visibleOnlyAdmin = authWrapper({
	authenticatedSelector: state => Object.keys(state.user.data).length !== 0 && state.user.isAuthenticated === true && state.user.data.role === 'admin',
	wrapperDisplayName: 'VisibleOnlyAdmin',
});

class Blabla {
render() {
  return (
    <div>
       <visibleOnlyAdmin>
            ....
       </visibleOnlyAdmin>
    </div>
  )
}
}
```
if I change name with first lowercase symbol - all work(( it's magic?

**Comment by mjrussell** [comment]
Please make sure you have read the documentation about higher order components [here](https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/Overview.html) and I encourage you to also read Dan's post [here](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) and the [react documentation](https://facebook.github.io/react/docs/higher-order-components.html) about it.

You are taking a higher order component (`VisibleOnlyAdmin`) which is a function, and trying to render it using jsx. But it is a function, not a component. You have to apply a higher order component to a component first in order to get a new component that is "wrapped". 

```js
import { VisibleOnlyAdmin } from 'app/common/acl';

const MyVisibleOnlyAdminComponent = VisibleOnlyAdmin(MyComponent);
...
render() {
  return (
    <div>
      <MyVisibleOnlyAdminComponent />
    </div>
  )
}
```
