### ISSUE TITLE
NavLink in a Component wrapped with connectedAuthWrapper not matching routes.

### ISSUE THREAD

**Issue by mapes911** [mjrussell/redux-auth-wrapper#226]
I'm not sure if this is a bug, or a misconfiguration on my part.
But I have a NavLink inside of a Component, that is wrapped with connectedAuthWrapper.

I am using the following packages

```
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-auth-wrapper": "^2.0.2",
```

This is my wrapper implementation

```
import { connectedRouterRedirect } from 'redux-auth-wrapper/history4/redirect'
export const loggedInVisible = connectedAuthWrapper({
  authenticatedSelector: state => state.authInfo.loggedIn === true,
  wrapperDisplayName: 'loggedInVisible',
});
```
Then the Component is wrapped with
```
const ChatRoomsAuthenticated = loggedInVisible(() => <ChatRooms />)
...
ReactDOM.render(
  <Provider store={store}>
    <Router>
      <div>
        <ChatRoomsAuthenticated />
        ....
      </div>
    </Router>
  <Provider>
```

Inside of ChatRooms I have another Component that has a NavLink

```
<NavLink to={`/room/${props.room.id}`}>{props.room.name}</NavLink>
```

When the route matches the specific link, it does not get an active class applied.
However, if I remove the wrapping and simply use the ChatRooms Component, the active class is applied correctly.

Am I missing some configuration to allow for the proper location to be shared to any child Components?

Thanks in advance for taking a look!

**Comment by mjrussell** [comment]
I think the issue is that you are throwing away the `location` prop when you render your chatRooms:

When you do this - `const ChatRoomsAuthenticated = loggedInVisible(() => <ChatRooms />)`, you are applying an HOC to a function component that renders `ChatRooms`. Note that you introduced in intermediary component here, instead of just applying the HOC directly to `ChatRooms`. 

So whats happening here is that `NavLink` expects to receive as props the `location`, but your `() => <ChatRooms />` discards props from the parent (in this case the auth HOC). So if you did something like `loggedInVisible((location) => <ChatRooms location={location} />)` I think it would work, as long as the auth HOC correctly passes the location through (which I think it does). 

I think the simplest thing is just remove the extra function component and do `const ChatRoomsAuthenticated = loggedInVisible( ChatRooms)` If that doesn't work you might need to apply the `withRouter` HOC from react router to also pass the `location` around

**Comment by mapes911** [comment]
Thanks for this @mjrussell 
This worked for me:

Replacing.

`const ChatRoomsAuthenticated = loggedInVisible(() => <ChatRooms />)`

with

`const ChatRoomsAuthenticated = withRouter(loggedInVisible(ChatRooms));`
