### ISSUE TITLE
Concatenating user auth

### ISSUE THREAD

**Issue by juanda99** [mjrussell/redux-auth-wrapper#32]
Whats the point about wrapping auth class twice?:

`     <Route path="admin" component={UserIsAuthenticated(UserIsAdmin(Admin))}/>`

I'm just using it once and the result is the same, but I'm sure there's something I can't see.

By the way, wrapperDisplayName should appear in DevTools? Because it just print the action name, USER_LOGGED_IN

This is my code:
```
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated'
})
const UserIsAdmin = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAdmin',
  predicate: user => user.isAdmin
})

ReactDOM.render(
  <Provider store={store}>
    <div>
      <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={Home}/>
          <Route path="login" component={Login}/>
          <Route path="foo" component={UserIsAuthenticated(Foo)}/>
          <Route path="admin" component={UserIsAdmin(Admin)}/>
        </Route>
      </Router>
      <DevTools />
    </div>
  </Provider>,
  document.getElementById('mount')
```
This is yours:
```
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated'
})
const UserIsAdmin = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  failureRedirectPath: '/',
  wrapperDisplayName: 'UserIsAdmin',
  predicate: user => user.isAdmin,
  allowRedirectBack: false
})

ReactDOM.render(
  <Provider store={store}>
    <div>
      <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={Home}/>
          <Route path="login" component={Login}/>
          <Route path="foo" component={UserIsAuthenticated(Foo)}/>
          <Route path="admin" component={UserIsAuthenticated(UserIsAdmin(Admin))}/>
        </Route>
      </Router>
      <DevTools />
    </div>
  </Provider>,
  document.getElementById('mount')
)
```

**Comment by mjrussell** [comment]
> wrapperDisplayName should appear in DevTools?

Its used to show a useful component name in the React DevTools like below: 
![image](https://cloud.githubusercontent.com/assets/1641895/14822614/33e4cb90-0b84-11e6-9bb5-3209f527ae16.png)
Its common to do so when using HOC to indicate clearly what the wrapper provides.

> Whats the point about wrapping auth class twice?:

The difference between your example and mine is in how the redirect happens for admin. To be fair its somewhat nit-picky but there are a few differences:

1. Users who are not admins will be redirected to `/login`, while in mine they will go to `/app` (if they are not authenticated - more on that below). Your example also will include a `redirect` query param when sending them back to `/login`

   Solving those issues are as easy as adding `failureRedirectPath: '/',` and `allowRedirectBack: false`.

2. The more subtle benefit of wrapping my two auth checks is in how unauthenticated admin users will be redirected. Because I have the redirect false for Admin (because we don't want regular users to keep trying to go back to /admin) it would result in non-authenticated admin users who typed the url in directly being redirected just to the home page after logging in. With the nested wrapping, I get the behavior I want where unauthenticated users go to login first (with the redirect back to /admin) and if they are admin they are let through, if not, they get redirect to the main app section without any redirect back parameter.

Let me know if that makes sense, I tried to describe why to use the double checks the README [here](https://github.com/mjrussell/redux-auth-wrapper#authorization--more-advanced-usage) if you have some thoughts on improving it, let me know.

**Comment by juanda99** [comment]
Upps my fault! When your Readme said about React DevTools I was thinking about redux devTools
Ok, your example now makes sense. Thank you!
