### ISSUE TITLE
UserAuthWrapper don't re-check for authentication

### ISSUE THREAD

**Issue by stepankuzmin** [mjrussell/redux-auth-wrapper#39]
Hi there! I'm using Immutable.js, so my whole state is immutable.

I've build wrapper with:

```js
import { push } from 'react-router-redux'

const userIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.get('auth').toJS(),
  redirectAction: push,
  predicate: auth.isAuthenticated
})
```

But UserAuthWrapper don't re-check for authentication after I change `isAuthenticated` to `true` (e.g. neither `authSelector` not `predicate` is called). What am I missing?

**Comment by mjrussell** [comment]
Can you include a gist or example project? 

Also are you including redirect logic in a Login container or something similar like the example [here](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/basic/components/Login.js#L31)

**Comment by stepankuzmin** [comment]
Thanks for reply @mjrussell! Mea culpa, I didn't include redirect logic to Login component. Closing issue.

**Comment by blocka** [comment]
To use the redirect logic requires stateful component (so that it calls `componentWillReceiveProps`). How would you do this if you're login component was a stateless function component?

**Comment by mjrussell** [comment]
@blocka redirecting a URL is a side effect and therefore its impossible to redirect from a stateless function component because the function components must be pure without side effects. The cleanest solution is probably to write an HOC for login that is stateful which wraps a stateless function component used for the presentation of login. I've been meaning to export an HOC for login (see #2) but haven't gotten around to it yet.
