### ISSUE TITLE
User object is loaded async and not ready when userAuthWrapper does it's thing

### ISSUE THREAD

**Issue by Marinolinderhof** [mjrussell/redux-auth-wrapper#55]
1. So the userAuthWrapper is in place and it works 
2. The user is loaded async (via saga) to retrieve the userObj.
3. the routing kicks in and userAuthWrapper checks the state for my userObj
4. my async call isn't ready. 
5. userAuthWrapper redirects me to /Login
6. async call is ready state changes with data userObj 
7 userAuthWrapper rechecks is called and rechecks (but is to late because my path is /login) 

So what to do? 
i made an other wrapper something like 
`
loadUserPromise.then( () => { DO_AUTHENTICATION_WRAPPER()  });
`

But i'm not sure this is how things should be like. 

oh and could some one explain the authenticatingSelector and (authSelector)

Thanks in advance
Marino.

**Comment by mjrussell** [comment]
@Marinolinderhof the `authenticatingSelector` was created exactly for the example you are describing.

First some details on `authenticatingSelector` and `authSelector`

Both `authenticatingSelector` and `authSelector` are redux selectors, meaning they select a piece of the redux store to pass to the UserAuthWrapper. If you use react-redux's `connect`, they expect the same arguments as `mapStateToProps` which is the first argument to `connect`. 

The `authSelector` is used to return to the auth wrapper the user object to use for determining if the user is logged in. If you don't override the `predicate` option, then by default the auth wrapper will perform a redirect if the `authSelector` returns `{}` or `null` when applied to the state object.

The `authenticatingSelector` also is used to pull data out of the store, but instead of returning the user object like the `authSelector`, it returns true or false depending on if the app is currently logging in the user (i.e. loading).

In your use case, it sounds like you should dispatch a redux action when your saga makes the request to log in the user (setting some field in a reducer such as `authenticating: true`), and then add the `authenticatingSelector` to your auth wrapper config to pull that field out of the store.

When this `authenticatingSelector` returns true, the auth wrapper will render the `LoadingComponent` config parameter which defaults to a `<span />` if not specified.


Does that help answer your question?

**Comment by Marinolinderhof** [comment]
Thank you so much for your answer. I'm doing that right so. 

My solution will be a state called init (where i will do the first time) and loaded when some uses the login page. 

if someone is interested in a follow up let me know.

**Comment by mjrussell** [comment]
Glad that worked for you!
