### ISSUE TITLE
Is it easily to hack into protected site?

### ISSUE THREAD

**Issue by chaintan17** [mjrussell/redux-auth-wrapper#68]
I'm using this library without server side rendering.
Meaning that, all components are actually written in Javascript.

So, i wonder would it easily as an intruder to get into the information without logging in the application?

**Comment by rewop** [comment]
It doesn't change much, as long as your backend doesn't allow access to information if somebody hacks. 

Consider this scenario. You protect your app with `redux-auth-app` to not show the page of a user if she is not logged in. 

So if the user is logged in, it means that your app has a token generated when the user logged in. So your app, after validating the token with your backedn, shows the profile page by fetchingthe content with a call to your backend (your request should send the token to the backend). The api should be able to understand if the user is logged in (by using of the token) and it returns the contents requested, usually in JSON format.

Now if the user is not logged in, your application would never show that page, because there is no token, or the token you have is not valid. However the user could still call your backend to try to fetch the profile contents. But not having a valid token, the backed should respond with an not authorised error. This way your contents are safe.

Therefore, as long as you don't put sensitive information in you javascript code, the security for this kind of scenario would be handled by your api.

Consider that `redux-auth-wrapper` does not solve any security issue, but it only allows you to build logic in your UI that is dependent on which permissions the current user has.

**Comment by mjrussell** [comment]
@rewop had a really good response, I just want to highlight a key point in there.

This library should be used only to hide pages that the user is not authenticated or authorized to view, not hide sensitive information already store on the client. You should assume that a nefarious user could indeed change their redux-store in a way as to gain access to a protected section of your site (or enable some components/functionality that only a subset of users can use).

However, the data and actions inside these protected views should be retrieved from/call APIs on a server that check for the authentication/authorization of the user (using a cookie, session token or some other means) and so if the user is able to navigate to say the admin section, they wouldn't see any data loaded or be able to successfully send an API call for an admin-protected action.

**Comment by chaintan17** [comment]
Thanks! @mjrussell @rewop for your time for answering this simple question. It's much clearer to me now. So, all sensitive stuff should still be loaded from backend using token as an authentication. I will close this issue :)

**Comment by chaintan17** [comment]
Oh, and i saving token in either cookie or session are save? (or localStorage?)
If somebody have an access to that computer, will they easily retrieve token and pretend to be somebody?

Thank you.

**Comment by mjrussell** [comment]
There's a lot of discussion about the tradeoffs between them and I don't think I could do it justice on github. Here is a pretty good write up though - https://auth0.com/blog/cookies-vs-tokens-definitive-guide/
