### ISSUE TITLE
unmount my child component on each location change

### ISSUE THREAD

**Issue by gjorgic** [mjrussell/redux-auth-wrapper#94]
hi
i have problem with nested routes;
After loggedin i store user data into `state.userSession.user`.
Each time when i click on sidebar link and transit from `Foo` to `Bar` or from `Bar` to `Foo` __whole App component was unmounted and then again mounted__
I use CSS transitions so whole content disappears on few moments, instead changing only `Foo` or `Bar` component inside parent `App` component

Seams to me that wrapper on each `LOCATION_CHANGE`  checks again if user is logged in and destroy child components and then rerender them;

#### Note
I use [Dynamic Routing](https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md). This below is just an example of the structure.
```jsx
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { replace } from 'react-router-redux';

const UserIsAuthenticated = UserAuthWrapper({
    authSelector: state => state.userSession.user,
    predicate: user => user && user.type == 'user',
    wrapperDisplayName: 'UserIsUserAuthorizationWrapper',
    failureRedirectPath: '/',
    redirectAction: newLoc => dispatch => {
        dispatch(replace(newLoc));
    }
})

const SidebarMenu = () => (
    <ul>
        <li><Link /></li>
        <li><Link /></li>
    </ul>)

const App = ({children}) => {
    return (
        <div>
            <div className="left-sidebar">
                <SidebarMenu />
            </div>
            <div className="content">
                {children}
            </div>
        </div>)
}

const Foo = () ...
const Bar = () ...

ReactDOM.render(
    <Provider store={store}>
        <Router history={history}>
            <Route path="/app" component={UserIsAuthenticated(App)}>
                <Route path="/app/foo" component={Foo}/>
                <Route path="/app/bar" component={Bar}/>
            </Route>
        </Router>
    </Provider>,
    document.getElementById('mount')
)
```

**Comment by mjrussell** [comment]
Hi @gjorgic this is most likely because you are applying the HOC inside your `getComponent` method on the route. The problem with doing this is that each time `getComponent` is called (which is every time the route is changed) it will re-run the `getComponent`, return a "new" component and React doesn't see them as being equal and will unmount it.

That is why I recommend for anyone using `getComponent` to apply their HOCs inside the component definition files. There are some instructions in the README [here](https://github.com/mjrussell/redux-auth-wrapper#where-to-define--apply-the-wrappers) and more info on the issue [here](https://github.com/mjrussell/redux-auth-wrapper/issues/44#issuecomment-226477903)

**Comment by gjorgic** [comment]
I move applying HOC outside of `getComponent` function and now works fine. Thx
