### ISSUE TITLE
About react-router-redux

### ISSUE THREAD

**Issue by NE-SmallTown** [mjrussell/redux-auth-wrapper#96]
Hello, I notice that the doc's(i.e. readme.md) examples are based on  react-router-redux except the last one, can you give the version that doesn't use react-router-redux.

Thanks.

**Comment by mjrussell** [comment]
The only hook-in to react-router-redux is the `redirectAction` parameter. If omitted it will use React Router's context directly for navigation. So if you want to use it without react-router-redux, just remove that parameter and any store config for react-router-redux in the example. So the basic HOC would be:

```js
// Redirects to /login by default
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user, // how to get the user state
  wrapperDisplayName: 'UserIsAuthenticated' // a nice name for this auth check
})
```

**Comment by NE-SmallTown** [comment]
@mjrussell Thanks for your answer. The main cause of committing this question is that I read the read-me about react-router-redux before, I find that I maybe don't need it, and [the link](http://stackoverflow.com/questions/36722584/how-to-sync-redux-state-and-url-hash-tag-params/36749963#36749963) it gives is also a good answer.

So could you tell me why you use react-router-redux, what's the advantage of that.

And one more question lastly, has this library thought about the token like [jwt](https://jwt.io/).I find that it's a important role in authorization, sorry about that I just learn this library right now, so these are my congfusing.

Thanks again.

**Comment by mjrussell** [comment]
If you don't think you need react-router-redux then I agree it is not necessary to add it to your dependencies. In the examples, I find it useful to include because users can see the redux actions fired off when the router changes locations (urls) using devTools or logger-middleware. In some of my projects I want to save routing information in the store or trigger trigger route changes by dispatching actions instead of using the singleton. In these cases it makes sense to use react-router-redux, but don't feel like you have to.

There have been a few discussions about handling tokens and invalidating them. Ultimately this library does not force users into one way of dealing with the token. Check out https://github.com/mjrussell/redux-auth-wrapper/issues/42 for some discussions on JWT storage and invalidation and the example of JWT located [here](https://github.com/mjrussell/react-redux-jwt-auth-example/tree/react-router-redux). You can ignore the react-router-redux pieces. If you still have questions after that feel free to ask them

**Comment by NE-SmallTown** [comment]
@mjrussell Thank you again for clearing my doubts.

**Comment by futuregerald** [comment]
I came across this because I'm not using react-router-redux. But what I really need to do is have it launch an action that has axios and thunk in it anytime someone visits certain pages. Can this be done without using redirectAction?

**Comment by futuregerald** [comment]
@mjrussell You're right, thank you. I ended up writing my own HOC to run the action with the ping to check if the access-token was good and return the user data. my HOC just does the ping but continues to load the page. I'm still using this wrapper though on certain pages that the user can't access at all unless they are logged in. Thanks for the feedback and for helping me figure out how to proceed with my project.

**Comment by bassbump** [comment]
I think an example without react-router-redux, with either an addendum for usage with react-router-redux or standalone as an example would be more accessible.
